import { type NextRequest, NextResponse } from "next/server"
import { jsPDF } from "jspdf"

export async function POST(request: NextRequest) {
  try {
    const { title, content, toolType, createdAt, metadata } = await request.json()

    if (!title || !content) {
      return NextResponse.json({ error: "Title and content are required" }, { status: 400 })
    }

    // Create PDF
    const doc = new jsPDF()

    // Add header background
    doc.setFillColor(37, 99, 235)
    doc.rect(0, 0, 210, 40, "F")

    // Add title
    doc.setTextColor(255, 255, 255)
    doc.setFont("helvetica", "bold")
    doc.setFontSize(20)
    doc.text(title, 20, 25)

    // Add tool type and generation date
    doc.setFontSize(10)
    if (toolType) {
      doc.text(`Tool: ${toolType.replace("-", " ").replace(/\b\w/g, (l) => l.toUpperCase())}`, 20, 32)
    }
    doc.text(`Created: ${new Date(createdAt).toLocaleDateString()}`, 150, 32)

    // Reset text color for body
    doc.setTextColor(0, 0, 0)
    doc.setFont("helvetica", "normal")

    const yPosition = 60

    // Add content
    doc.setFontSize(12)
    const splitContent = doc.splitTextToSize(content, 170)
    doc.text(splitContent, 20, yPosition)

    // Add metadata if available
    if (metadata && Object.keys(metadata).length > 0) {
      let metadataY = yPosition + splitContent.length * 7 + 20
      
      doc.setFont("helvetica", "bold")
      doc.setFontSize(14)
      doc.text("Additional Details:", 20, metadataY)
      
      doc.setFont("helvetica", "normal")
      doc.setFontSize(10)
      metadataY += 10
      
      Object.entries(metadata).forEach(([key, value]) => {
        if (value && typeof value === 'string') {
          const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
          doc.text(`${label}: ${value}`, 20, metadataY)
          metadataY += 7
        }
      })
    }

    // Add footer
    const pageCount = doc.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFillColor(248, 250, 252)
      doc.rect(0, 280, 210, 17, "F")
      doc.setFontSize(9)
      doc.setTextColor(100, 116, 139)
      doc.text("Generated by The Next Level U", 20, 290)
      doc.text(`Page ${i} of ${pageCount}`, 170, 290)
    }

    // Generate PDF buffer
    const pdfBuffer = Buffer.from(doc.output("arraybuffer"))

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}.pdf"`,
      },
    })
  } catch (error) {
    console.error("Error generating PDF:", error)
    return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 })
  }
}
