import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: NextRequest) {
  try {
    const { to, subject, script, tool, recipientEmail } = await req.json()

    console.log('Send script email called:', { to, subject, tool, recipientEmail })

    if (!subject || !script) {
      return NextResponse.json({ error: 'Subject and script are required' }, { status: 400 })
    }

    let emailTo = ''
    let emailSubject = ''

    if (to === 'self') {
      // Get user email from headers or use a default
      const userEmail = req.headers.get('x-user-email') || 'mikepuma@c21be.com'
      emailTo = userEmail
      emailSubject = `[${tool}] ${subject}`
    } else if (to === 'recruit' && recipientEmail) {
      emailTo = recipientEmail
      emailSubject = subject
    } else {
      return NextResponse.json({ error: 'Invalid recipient' }, { status: 400 })
    }

    const emailContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2>${subject}</h2>
        <div style="background-color: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <pre style="white-space: pre-wrap; font-family: Arial, sans-serif; margin: 0;">${script}</pre>
        </div>
        <p style="color: #666; font-size: 14px;">
          Generated by ${tool} - Empower AI Platform
        </p>
      </div>
    `

    const { data, error } = await resend.emails.send({
      from: 'Empower AI <noreply@getempowerai.com>',
      to: emailTo,
      subject: emailSubject,
      html: emailContent,
    })

    if (error) {
      console.error('Resend error:', error)
      return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
    }

    return NextResponse.json({ 
      success: true, 
      messageId: data?.id,
      message: 'Email sent successfully'
    })

  } catch (error) {
    console.error('Send script email error:', error)
    return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
  }
}