import { NextResponse } from "next/server"
import { Resend } from "resend"

export async function POST() {
  try {
    console.log("=== SCRIPT EMAIL TEST ===")
    console.log("API Key exists:", !!process.env.RESEND_API_KEY)
    console.log("API Key preview:", process.env.RESEND_API_KEY?.substring(0, 10) + "...")

    const resend = new Resend(process.env.RESEND_API_KEY)

    // Test data similar to what the Property Script Generator would send
    const testData = {
      to: "mikepuma@c21be.com",
      name: "Mike Puma",
      script: "This is a test property script to verify the email functionality is working correctly. It should include property details and be properly formatted.",
      formData: {
        deliveryMethod: "phone",
        prospectType: "fsbo",
        customProspectType: "",
        language: "English",
        tonality: "Professional & Authoritative",
        agentName: "Mike Puma",
        brokerageName: "Century 21 Beggins",
        agentEmail: "mikepuma@c21be.com",
        additionalDetails: "Test additional details",
        propertyAddress: "123 Test Street, Test City, CA 90210",
        ownerNames: ["John Doe", "Jane Doe"],
        propertyType: "Single Family Home",
        estimatedValue: "$750,000",
        propertyDetails: "Beautiful 3-bedroom home with updated kitchen"
      }
    }

    const response = await resend.emails.send({
      from: "Mike Puma - The Next Level U <noreply@marketing.getempowerai.com>",
      to: [testData.to],
      subject: `TEST: Your Phone Call Script for FSBO - Property: 123 Test Street by The Next Level U`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #ffffff;">
          <div style="background: linear-gradient(135deg, #ea580c, #dc2626); padding: 30px; text-align: center;">
            <h1 style="color: white; margin: 0; font-size: 28px;">Your Script is Ready!</h1>
            <p style="color: white; margin: 15px 0 0 0; font-size: 16px;">Generated by Property Script Generator - The Next Level U</p>
          </div>
          
          <div style="padding: 30px; background: #f9fafb;">
            <h2 style="color: #1f2937; margin-bottom: 20px; font-size: 24px;">Hi ${testData.name},</h2>
            
            <p style="color: #4b5563; line-height: 1.6; font-size: 16px;">
              Your professional <strong>phone call script</strong> for <strong>FSBO (For Sale By Owner)</strong> at <strong>123 Test Street</strong> has been generated! This script incorporates DISC behavioral principles and VAK sensory language for maximum effectiveness.
            </p>
            
            <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin: 20px 0; border: 1px solid #0ea5e9;">
              <h4 style="color: #0c4a6e; margin: 0 0 10px 0; font-size: 16px;">🏠 Property Details:</h4>
              <p style="color: #0c4a6e; margin: 0; font-size: 14px;">
                <strong>Address:</strong> 123 Test Street, Test City, CA 90210<br>
                <strong>Type:</strong> Single Family Home<br>
                <strong>Estimated Value:</strong> $750,000<br>
                <strong>Owners:</strong> John Doe, Jane Doe
              </p>
            </div>
            
            <div style="background: white; padding: 25px; border-radius: 8px; margin: 25px 0; border-left: 4px solid #ea580c; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
              <h3 style="color: #1f2937; margin-top: 0; font-size: 18px;">Your Professional Script:</h3>
              <div style="color: #4b5563; line-height: 1.6; white-space: pre-wrap; font-size: 15px; border: 1px solid #e5e7eb; padding: 15px; border-radius: 4px; background: #f8f9fa; max-height: 300px; overflow-y: auto;">
                ${testData.script}
              </div>
            </div>
            
            <p style="color: #4b5563; line-height: 1.6; font-size: 16px;">
              I've also attached a beautifully formatted HTML version of your script that you can use for reference and training.
            </p>

            <div style="background: linear-gradient(135deg, #fef3c7, #fde68a); padding: 20px; border-radius: 8px; margin: 25px 0; border: 1px solid #f59e0b;">
              <h4 style="color: #92400e; margin: 0 0 15px 0; font-size: 16px;">💡 How to Use Your Script:</h4>
              <ul style="color: #78350f; margin: 0; padding-left: 20px; line-height: 1.6;">
                <li style="margin-bottom: 5px;">Practice the script until it feels natural</li>
                <li style="margin-bottom: 5px;">Customize it with specific details for each prospect</li>
                <li style="margin-bottom: 5px;">Use the DISC and VAK principles to adapt your delivery</li>
                <li style="margin-bottom: 5px;">Focus on the call-to-action at the end</li>
                <li style="margin-bottom: 5px;">Track your results and refine as needed</li>
                <li>Print for easy reference during calls</li>
              </ul>
            </div>
            
            <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin: 25px 0; border: 1px solid #0ea5e9;">
              <p style="color: #0c4a6e; margin: 0; font-size: 14px; text-align: center;">
                <strong>Need more scripts?</strong> Visit our AI Hub for 10 more powerful real estate tools!
              </p>
            </div>
            
            <p style="color: #6b7280; font-size: 14px; line-height: 1.6; margin-top: 30px;">
              Best regards,<br>
              <strong>Mike Puma</strong><br>
              The Next Level U Team<br>
              <a href="mailto:MikePuma@c21be.com" style="color: #ea580c; text-decoration: none;">MikePuma@c21be.com</a>
            </p>
          </div>
          
          <div style="background: #1f2937; padding: 25px; text-align: center;">
            <p style="color: #9ca3af; margin: 0; font-size: 14px;">
              © 2024 The Next Level U. Empowering real estate professionals with AI-powered tools.
            </p>
            <p style="color: #6b7280; margin: 10px 0 0 0; font-size: 12px;">
              This email was generated by our Property Script Generator AI tool. Visit us for more real estate solutions.
            </p>
          </div>
        </div>
      `,
    })

    console.log("Resend response:", response)

    if (response.error) {
      return NextResponse.json({
        success: false,
        error: response.error.message,
        details: response.error,
      })
    }

    return NextResponse.json({
      success: true,
      messageId: response.data?.id,
      message: "Test script email sent successfully to mikepuma@c21be.com",
    })
  } catch (error) {
    console.error("Script email test error:", error)
    return NextResponse.json({
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
      details: error,
    })
  }
}
