import { NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { email, agentName, agentEmail, marketType, searchQuery, marketData, timestamp } = body

    if (!email || !agentName || !searchQuery || !marketData) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      )
    }

    // Format market data for email
    const formatMarketData = (data: any) => {
      if (!data || typeof data !== 'object') {
        return { error: "No data available" }
      }

      try {
        if (data.market_overview) {
          return {
            type: 'housing',
            location: data.search_query || "Unknown Location",
            typicalHomeValue: data.market_overview.typical_home_values,
            description: data.market_overview.description,
            forSaleInventory: data.market_overview.for_sale_inventory,
            newListings: data.market_overview.new_listings,
            saleToListRatio: data.market_overview["market saletolist ratio"],
            aiInsights: data.ai_insights || null
          }
        }

        if (data.rental_data) {
          return {
            type: 'rental',
            location: data.search_query || "Unknown Location",
            averageRent: data.rental_data.average_rent,
            rentTrend: data.rental_data.rent_trend,
            rentalInventory: data.rental_data.rental_inventory,
            description: data.rental_data.description,
            aiInsights: data.ai_insights || null
          }
        }

        return {
          type: 'unknown',
          location: data.search_query || "Unknown Location",
          rawData: data
        }
      } catch (error) {
        return { error: "Unable to format data" }
      }
    }

    const formattedData = formatMarketData(marketData)

    // Create email content
    let emailContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #333; text-align: center;">Market Analysis Report</h1>
        <h2 style="color: #666; text-align: center;">${marketType === 'housing' ? 'Housing' : 'Rental'} Market Analysis for ${searchQuery}</h2>
        <p style="color: #666; text-align: center;">Analyzed by ${agentName} on ${new Date(timestamp).toLocaleDateString()}</p>
        
        <hr style="margin: 20px 0;">
    `

    if (formattedData.type === 'housing') {
      emailContent += `
        <h3 style="color: #333;">Market Overview</h3>
        <ul style="list-style: none; padding: 0;">
          <li style="margin: 10px 0;"><strong>Typical Home Value:</strong> $${formattedData.typicalHomeValue?.toLocaleString() || 'N/A'}</li>
          <li style="margin: 10px 0;"><strong>For Sale Inventory:</strong> ${formattedData.forSaleInventory?.toLocaleString() || 'N/A'}</li>
          <li style="margin: 10px 0;"><strong>Sale/List Ratio:</strong> ${formattedData.saleToListRatio || 'N/A'}</li>
        </ul>
      `
    } else if (formattedData.type === 'rental') {
      emailContent += `
        <h3 style="color: #333;">Rental Market Overview</h3>
        <ul style="list-style: none; padding: 0;">
          <li style="margin: 10px 0;"><strong>Average Rent:</strong> $${formattedData.averageRent?.toLocaleString() || 'N/A'}</li>
          <li style="margin: 10px 0;"><strong>Rental Inventory:</strong> ${formattedData.rentalInventory?.toLocaleString() || 'N/A'}</li>
          <li style="margin: 10px 0;"><strong>Rent Trend:</strong> ${formattedData.rentTrend || 'N/A'}</li>
        </ul>
      `
    }

    if (formattedData.description) {
      emailContent += `
        <h3 style="color: #333;">Market Description</h3>
        <p style="line-height: 1.6;">${formattedData.description}</p>
      `
    }

    if (formattedData.aiInsights) {
      emailContent += `
        <h3 style="color: #333;">AI Market Analysis</h3>
        <div style="background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 15px 0;">
          <p style="line-height: 1.6; white-space: pre-line;">${formattedData.aiInsights}</p>
        </div>
      `
    }

    emailContent += `
        <hr style="margin: 20px 0;">
        <p style="color: #666; text-align: center; font-size: 12px;">
          This report was generated by MyMarket AI. For questions, contact ${agentEmail || 'your agent'}.
        </p>
      </div>
    `

    const { data, error } = await resend.emails.send({
      from: "MyMarket AI <noreply@empowerai.com>",
      to: [email],
      subject: `${marketType === 'housing' ? 'Housing' : 'Rental'} Market Analysis for ${searchQuery}`,
      html: emailContent,
    })

    if (error) {
      console.error("Resend error:", error)
      return NextResponse.json(
        { error: "Failed to send email" },
        { status: 500 }
      )
    }

    return NextResponse.json({ success: true, data })
  } catch (error) {
    console.error("Email send error:", error)
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    )
  }
} 