import { NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  try {
    const { to, name, description, propertyAddress, listingPrice, listingHTML } = await request.json()

    if (!to || !name || !description) {
      return NextResponse.json(
        { error: "Missing required fields: to, name, description" },
        { status: 400 }
      )
    }

    const emailHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>Property Listing: ${propertyAddress}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
            }
            .header {
              background: #b6a888;
              color: white;
              padding: 30px;
              text-align: center;
              margin-bottom: 30px;
              border-radius: 8px;
            }
            .header h1 {
              margin: 0;
              font-size: 28px;
            }
            .header p {
              margin: 10px 0 0;
              font-size: 16px;
            }
            .property-title {
              font-size: 24px;
              font-weight: bold;
              margin-bottom: 5px;
              color: #1f2937;
            }
            .property-price {
              font-size: 22px;
              color: #b6a888;
              margin-bottom: 20px;
              font-weight: bold;
            }
            .divider {
              border-top: 1px solid #e5e7eb;
              margin: 20px 0;
            }
            .description {
              font-size: 16px;
              line-height: 1.8;
              margin-bottom: 30px;
              color: #374151;
            }
            .footer {
              background: #f9fafb;
              border-top: 1px solid #e5e7eb;
              padding: 20px;
              text-align: center;
              font-size: 12px;
              color: #6b7280;
              margin-top: 40px;
              border-radius: 8px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Property Listing</h1>
            <p>Generated by ListIT - The Next Level U</p>
          </div>
          
          <div class="property-title">${propertyAddress}</div>
          <div class="property-price">${listingPrice}</div>
          
          <div class="divider"></div>
          
          <div class="description">
            ${description.replace(/\n/g, '<br>')}
          </div>
          
          <div class="footer">
            <p>This listing description was generated by ListIT AI tool.</p>
            <p>For questions about this property, please contact ${name}.</p>
          </div>
        </body>
      </html>
    `

    const { data, error } = await resend.emails.send({
      from: "ListIT <noreply@getempowerai.com>",
      to: [to],
      subject: `Listing Description: ${propertyAddress}`,
      html: emailHtml,
    })

    if (error) {
      console.error("Resend error:", error)
      return NextResponse.json(
        { error: "Failed to send email" },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      messageId: data?.id,
      message: "Listing description sent successfully"
    })

  } catch (error) {
    console.error("Error sending listing email:", error)
    return NextResponse.json(
      { error: "Failed to send email" },
      { status: 500 }
    )
  }
}
