import { NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  try {
    const { to, name, description, propertyAddress, listingPrice, listingHTML } = await request.json()

    // Validate required fields
    if (!to || !name || !description) {
      return NextResponse.json(
        { error: 'Missing required fields: to, name, description' },
        { status: 400 }
      )
    }

    if (!process.env.RESEND_API_KEY) {
      console.error("RESEND_API_KEY is missing!")
      return NextResponse.json({ 
        error: "Email service not configured - RESEND_API_KEY environment variable is missing",
        details: {
          message: "The RESEND_API_KEY environment variable is required for sending emails",
          solution: "Add RESEND_API_KEY to your environment variables or deployment configuration",
          currentEnv: process.env.NODE_ENV,
          isVercel: !!process.env.VERCEL
        }
      }, { status: 500 })
    }

    console.log("Sending listing email via Resend to:", to)
    console.log("Environment info:", {
      hasApiKey: !!process.env.RESEND_API_KEY,
      environment: process.env.NODE_ENV,
      isVercel: !!process.env.VERCEL
    })

    // Create email content
    let emailContent: string
    try {
      emailContent = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px;">
            Your Professional Listing Description
          </h2>
          
          <p><strong>Hello ${name},</strong></p>
          
          <p>Here's your personalized listing description:</p>
          
          <div style="background-color: #f8fafc; border-left: 4px solid #2563eb; padding: 20px; margin: 20px 0; border-radius: 4px;">
            <div style="white-space: pre-wrap; font-family: 'Courier New', monospace; line-height: 1.6;">
              ${description}
            </div>
          </div>
          
          <div style="background-color: #f0f9ff; border: 1px solid #0ea5e9; padding: 15px; border-radius: 4px; margin: 20px 0;">
            <h4 style="margin: 0 0 10px 0; color: #0369a1;">Property Details:</h4>
            <ul style="margin: 0; padding-left: 20px;">
              <li><strong>Address:</strong> ${propertyAddress || 'N/A'}</li>
              <li><strong>Listing Price:</strong> ${listingPrice || 'N/A'}</li>
              <li><strong>Description Length:</strong> ${description.length} characters</li>
            </ul>
          </div>
          
          <p style="color: #6b7280; font-size: 14px;">
            This listing description was generated using AI-powered tools and is optimized for maximum buyer engagement.
            Customize it further based on your specific property and market.
          </p>
          
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;">
          
          <p style="color: #6b7280; font-size: 12px; text-align: center;">
            Generated by Empower AI - Professional Real Estate Listings
          </p>
        </div>
      `
      console.log("Email content created successfully, length:", emailContent.length)
    } catch (contentError) {
      console.error("Error creating email content:", contentError)
      return NextResponse.json(
        { error: `Failed to create email content: ${contentError instanceof Error ? contentError.message : 'Unknown error'}` },
        { status: 500 }
      )
    }

    const result = await resend.emails.send({
      from: "ListIt AI <noreply@marketing.getempowerai.com>",
      to: [to],
      subject: `Your Professional Listing Description | Empower AI`,
      html: emailContent,
    })

    console.log("Email sent successfully via Resend:", result)

    return NextResponse.json({
      success: true,
      message: "Listing description email sent successfully",
      emailId: result.id
    })

  } catch (error) {
    console.error("Error in send-listing-email route:", error)
    
    if (error instanceof Error) {
      return NextResponse.json(
        { error: error.message },
        { status: 500 }
      )
    }
    
    return NextResponse.json(
      { error: "Failed to send listing description email" },
      { status: 500 }
    )
  }
}
