import { type NextRequest, NextResponse } from "next/server"
import nodemailer from "nodemailer"

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData()
    
    const analysis = formData.get("analysis") as string
    const agentName = formData.get("agentName") as string
    const propertyAddress = formData.get("propertyAddress") as string
    const email = formData.get("email") as string

    if (!analysis || !agentName || !email) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      )
    }

    console.log("RealDeal client email send request:", { agentName, email, propertyAddress })

    // Create Gmail transporter
    const transporter = nodemailer.createTransporter({
      host: "smtp.gmail.com",
      port: 587,
      secure: false,
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD,
      },
      tls: {
        rejectUnauthorized: false,
      },
    })

    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #f59e0b, #d97706); padding: 30px; border-radius: 10px; margin-bottom: 30px; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 28px; font-weight: bold;">Contract Analysis Report</h1>
          <p style="color: white; margin: 10px 0 0 0; font-size: 16px; opacity: 0.9;">Professional Real Estate Contract Review</p>
        </div>
        
        <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <h2 style="color: #1f2937; margin: 0 0 10px 0; font-size: 20px;">Property Details</h2>
          <p style="color: #6b7280; margin: 0; font-size: 16px;"><strong>Property:</strong> ${propertyAddress || "Not specified"}</p>
          <p style="color: #6b7280; margin: 5px 0 0 0; font-size: 16px;"><strong>Prepared by:</strong> ${agentName}</p>
          <p style="color: #6b7280; margin: 5px 0 0 0; font-size: 16px;"><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        </div>

        <div style="background-color: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 25px; margin-bottom: 20px;">
          <h2 style="color: #1f2937; margin: 0 0 20px 0; font-size: 22px; border-bottom: 2px solid #f59e0b; padding-bottom: 10px;">Contract Analysis</h2>
          <div style="line-height: 1.6; color: #374151; font-size: 16px;">
            ${analysis.replace(/\n/g, '<br>')}
          </div>
        </div>

        <div style="background-color: #f0f9ff; border-left: 4px solid #0ea5e9; padding: 20px; border-radius: 0 8px 8px 0; margin-bottom: 20px;">
          <h3 style="color: #0c4a6e; margin: 0 0 10px 0; font-size: 18px;">Important Disclaimer</h3>
          <p style="color: #0c4a6e; margin: 0; font-size: 14px; line-height: 1.5;">
            This analysis is generated by AI and should be reviewed by a qualified real estate professional. 
            Always consult with legal counsel for complex contract matters. This report is for informational purposes only.
          </p>
        </div>

        <div style="text-align: center; padding: 20px; border-top: 1px solid #e5e7eb; margin-top: 30px;">
          <p style="color: #6b7280; margin: 0; font-size: 14px;">
            Generated by RealDeal AI | The Next Level U
          </p>
          <p style="color: #9ca3af; margin: 5px 0 0 0; font-size: 12px;">
            This analysis was prepared by ${agentName}
          </p>
        </div>
      </div>
    `

    const mailOptions = {
      from: `"${agentName}" <${process.env.GMAIL_USER}>`,
      to: email,
      subject: `Contract Analysis Report - ${propertyAddress || "Real Estate Contract"}`,
      html: emailHtml,
    }

    console.log("Sending client email via Gmail...")
    const info = await transporter.sendMail(mailOptions)
    console.log("Client email sent successfully:", info.messageId)

    return NextResponse.json({
      success: true,
      messageId: info.messageId,
      message: "Contract analysis email sent to client successfully",
    })
  } catch (error) {
    console.error("=== REALDEAL CLIENT EMAIL SEND ERROR ===")
    console.error("Error details:", error)
    console.error("Error stack:", error instanceof Error ? error.stack : "No stack trace")

    return NextResponse.json(
      {
        success: false,
        error: `Failed to send client email: ${error instanceof Error ? error.message : "Unknown error"}`,
        details: error instanceof Error ? error.stack : error,
      },
      { status: 500 }
    )
  }
}
